### ISSUE TITLE
How to build and run the project

### ISSUE THREAD

**Issue by PabloReszczynski** [jendave/mochadoom#7]
Hello, I'm forking this project for uni this semester. But I'm having issues in building and running the game. I'm aware it uses gradle for building and there are some wads to use as examples, but can't really run the jar generated by gradle with the wads.

**Comment by AXDOOMER** [comment]
I had a lot of trouble with it when I was trying to run it. All I was able to do is to start it using the IDE (Eclipse). 

We should write some doc about this, so people would know how to start the engine, how to build a .jar and how to use it. 

(my fork: https://github.com/AXDOOMER/mochadoom)

**Comment by jendave** [comment]
The project uses Maven. Please use Maven from https://maven.apache.org. The build information is in the pom.xml file.
